spring:
  datasource:
    initialize: false
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:offer_owner;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=true;MODE=MYSQL
    username: sa
    password:
  hibernate:
    database: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create